### ISSUE TITLE
`gql.tada check` reports an "Unkown fragment" error when fragments are imported in a TS file from a Vue SFC

### ISSUE THREAD

**Issue by raphael-yapla** [0no-co/gql.tada#210]
### Describe the bug

We're trying to setup gql.tada to do a check in a CI job using the newly added check command (awesome addition btw!) but we're faced with a weird issue. The command will report incorrectly an error when fragments are imported from a different file type. This is what I've tested:

- ✅ Fragment imported in a TS file from another TS file
- ✅ Fragment imported in a Vue component from another Vue component file
- ❌ Fragment imported in a TS file from a Vue component file

The IDE however, is fine with any kind of combination. I'm unsure where the problem lies exactly but it seems strange that the IDE would not report the error if both the CLI and IDE are using the LSP?

I've set up a reproduction that hopefully will help you track the source down.

Thank you so much for the awesome project, it might be the best package I've used in a long time!

### Reproduction

https://github.com/raphael-yapla/gql-tada-vue-issue

### gql.tada version

gql.tada v1.5.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Does that actually work in a regular `tsc` run or not?
I'm not super familiar with how Volar works, but for our check command that definitely won't just work out of the box.

See:
- https://github.com/0no-co/GraphQLSP/issues/168
- https://github.com/0no-co/GraphQLSP/issues/242

**Comment by raphael-yapla** [comment]
No you'd have to use [vue-tsc](https://github.com/vuejs/language-tools) so that would makes sense.

The only thing I don't understand is how comes the check command works when importing to and from a Vue SFC file then?

**Comment by JoviDeCroock** [comment]
Yes, both for Svelte and Vue we could use their respective packages to do a prepass over all the files and make them into TS

- [SvelteTSX](https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx)
- [VueTSC](https://github.com/vuejs/language-tools)

Then add the `TS` equivalent of these files into `ts-morph` and run `check`

**Comment by kitten** [comment]
@JoviDeCroock Just to note this down somewhere, TS Morph seems to have an open issue for this but hasn't resolved this yet, but someone there basically pointed out the API to use for this on the TS side

**Comment by kitten** [comment]
Another comment here on this topic:
https://github.com/0no-co/gql.tada/issues/231#issuecomment-2065455186

The gist of it is though that currently we have no timeline or implementation path yet for Vue, Astro, and Svelte support, and haven't deprioritised this yet

**Comment by JoviDeCroock** [comment]
I do think we can make it work by doing things similar to https://github.com/sveltejs/language-tools/blob/master/packages/typescript-plugin/src/module-loader.ts#L97 but that is going to be a lot of work and essentially duplicates the Svelte TS Plugin 😅 which I preferably would not want to do, I do wonder what happens if one uses the `svelte` TS Plugin in combination with the LSP as they essentially mutate the module-loader, ... so in theory GraphQLSP should benefit from that, if that's the case then we only need to fix the for the CLI.

**Comment by JoviDeCroock** [comment]
I have an initial working version for this in #232 - would love for this to be tested on larger projects though 😅

**Comment by KammererTob** [comment]
I have tested the PR on my project, which contains >70 fragments and queries in various files (mostly .ts and .vue file), which nested fragments etc. The cache is now correctly populated, but it seems to break some typings (as far as i can tell only for fragments/queries which contain a fragment of another component). Here is an example (left without cache, right with cache).

![image](https://github.com/0no-co/gql.tada/assets/1510949/c37948d1-3680-4fcf-9704-cc1f5a3e29db)

`    "\n    fragment EventDialog on Event {\n      id\n      name\n      platform\n      discipline\n      ...EntityEditDialog\n    }\n  ":
      TadaDocumentNode<{ [x: string]: any; }, {}, { fragment: "EventDialog"; on: "Event"; masked: true; }>;`

If you need more information please let me know. I can also try to reproduce this in the reproduction i've provided in the linked issue if helpful.

**Comment by JoviDeCroock** [comment]
Was able to fix `check` and `generate persisted` but `turbo` is still a pain, looks like the `type-checker` isn't really willing to collaborate here 😅

**Comment by raphael-yapla** [comment]
Incredible, thank you so much for such a quick turnaround!
