### ISSUE TITLE
readFragment leaks "any" when used without generic & explicit fragment.

### ISSUE THREAD

**Issue by ariesclark** [0no-co/gql.tada#215]
### Describe the bug

```ts
declare const value: FragmentOf<...>
readFragment(value) // any.
```

### gql.tada version

1.5.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Nice catch! As far as I can tell, this should be a really simple and clean fix. PR is linked
