### ISSUE TITLE
Unknown directive "@_unmask" Vscode

### ISSUE THREAD

**Issue by tianyingchun** [0no-co/gql.tada#217]
### Describe the bug

if we have multi `fragment` declaration it always give me `Unknown directive "@_unmask"`

```ts filename="ViewWidgetEntity.ts"
import { graphql } from '@/apollo/graphql';

export const ViewWidgetEntity = graphql(`
// it correct for `@_unmask`
  fragment ViewWidgetEntity on ViewWidgetEntity @_unmask {
    id
    createdAt
    updatedAt
    displayOrder
    entityId
    entityName
    viewWidgetId
  }
`);

```

```ts filename="ViewWidget.ts"
import { graphql } from '@/apollo/graphql';

export const ViewWidget = graphql(`
// it give `Unknown directive "@_unmask".` error tips
  fragment ViewWidget on ViewWidget @_unmask {
    id
    createdAt
    updatedAt
    widgetGroupName
    widgetDesc
    widgetPreview
    widgetViewType
    widgetViewConfig
    languageCode
    translations {
      id
      languageCode
      widgetViewConfig
    }
  }
`);
```

<img width="536" alt="image" src="https://github.com/0no-co/gql.tada/assets/2833251/4afb643b-74b0-41bb-ade4-e35d8e50d7bf">

### gql.tada version

   "gql.tada": "1.5.1",
  "@0no-co/graphqlsp": "1.10.0",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by tianyingchun** [comment]
it just vscode IDE error tips, the application works fine

**Comment by JoviDeCroock** [comment]
What do you mean with `multi-fragment` maybe we are missing a filter [here](https://github.com/0no-co/GraphQLSP/blob/main/packages/graphqlsp/src/diagnostics.ts#L384-L392), a more hollistic solution would be to tweak [getDiagnostics](https://github.com/0no-co/GraphQLSP/blob/main/packages/graphqlsp/src/diagnostics.ts#L377) and use the [GraphQL AST instead](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service/src/utils/validateWithCustomRules.ts#L85-L96)

**Comment by tianyingchun** [comment]
it works

**Comment by kyrylofranko** [comment]
have you found a way to avoid this TS error? the same in Webstorm
<img width="498" alt="Screenshot 2024-08-04 at 22 21 19" src="https://github.com/user-attachments/assets/307fd0ba-6304-49dc-9212-bb13f2fadc4f">

**Comment by kitten** [comment]
@kyrylofranko This is Webstorm's built in GraphQL support, which at best you'd have to disable. Unfortunately, I'm not sure if they've resolved any issues regarding TypeScript plugins in general, and if `gql.tada` is now working there. But they responded to issues regarding TypeScript plugins with comments regarding their builtin functionality, which is a bit disappointing

**Comment by freddieerg** [comment]
@kyrylofranko I had this same issue. If you go into settings > editor > inspections then find graphql and disable "unresolved reference" the issue will go away.

**Comment by arcataroger** [comment]
> [@kyrylofranko](https://github.com/kyrylofranko) I had this same issue. If you go into settings > editor > inspections then find graphql and disable "unresolved reference" the issue will go away.

Thank you so much. That's what I had to do to finally get the `Unknown directive "_unmask"` error to go away in Webstorm. It took forever to find this answer, so leaving a more verbatim reply here just in case it helps someone else search.

Thanks again.
