### ISSUE TITLE
tadaTurboLocation and tadaPersistedLocation are now required in 1.6.1 when using multiple schemas

### ISSUE THREAD

**Issue by nathanchapman** [0no-co/gql.tada#269]
### Describe the bug

When omitting the `tadaTurboLocation` and `tadaPersistedLocation` fields when using multiple schemas, it results in the following errors:

```
 ⚠ Error
Failed to load configuration.
┗ All 'tadaTurboLocation' values in 'schemas' must be unique.

 ⚠ Error
Failed to load configuration.
┗ All 'tadaPersistedLocation' values in 'schemas' must be unique.
```

### gql.tada version

1.6.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This is intended behaviour, but the error messages are indeed a little misleading and too eager.
