### ISSUE TITLE
`turbo` cache is not including fragments that are defined separately (like fragment colocation)

### ISSUE THREAD

**Issue by dnlsandiego** [0no-co/gql.tada#289]
### Describe the bug

It looks like the `turbo` command isn't including fragments in the generated cache file. Which results in an incomplete `graphql-cache.d.ts`, breaking types in the editor.

I've created a small repo in the reproduction link. But it's basically the `example-pokemon-api` in the examples folder.
Given:
```tsx
// ./src/pokemon-item.tsx
export const PokemonItemFragment = graphql(`
  fragment PokemonItem on Pokemon {
    id
    name
  }
`);
```
```tsx
// ./src/pokemon.tsx
const PokemonsQuery = graphql(`
  query Pokemons ($limit: Int = 10) {
    pokemons(limit: $limit) {
      id
      ...PokemonItem
    }
  }
`, [PokemonItemFragment]);
```
 Running `gql.tada turbo` results in a [graphql-cache.d.ts](https://github.com/dnlsandiego/gql.tada-cache-issue/blob/main/src/graphql-cache.d.ts#L7) that has 

```ts
declare module 'gql.tada' {
 interface setupCache {
    "\n  query Pokemons ($limit: Int = 10) {\n    pokemons(limit: $limit) {\n      id\n      ...PokemonItem\n    }\n  }\n":
      TadaDocumentNode<{}, { limit?: number | null | undefined; }, { fragment: "Pokemons"; on: unknown; masked: true; }>;
  }
}
```
`PokemonItem` is being spread here but it's not included anywhere. Compared to when the fragment is in the same document:
```tsx
const PokemonsQuery = graphql(`
  query Pokemons ($limit: Int = 10) {
    pokemons(limit: $limit) {
      id
      ...PokemonItem
    }
  }
  fragment PokemonItem on Pokemon {
    id
    name
  }
`, []);
```
```ts
declare module 'gql.tada' {
 interface setupCache {
    "\n  query Pokemons ($limit: Int = 10) {\n    pokemons(limit: $limit) {\n      id\n      ...PokemonItem\n    }\n  }\n  fragment PokemonItem on Pokemon {\n    id\n    name\n  }\n":
      TadaDocumentNode<{}, { limit?: number | null | undefined; }, { fragment: "Pokemons"; on: unknown; masked: true; }>;
  }
}

```

A warning is also shown
```bash
  3:36  The discovered document is not of type "TadaDocumentNode".
        If this is unexpected, please file an issue describing your case.
 ```

### Reproduction

https://github.com/dnlsandiego/gql.tada-cache-issue

### gql.tada version

`gql.tada` `1.7.0`
`@0no-co/graphqlsp` `^1.12.2`

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
That's odd, somehow TypeScript is refusing to evaluate the symbol in the `pokemon-item.tsx` file. It finds the type however when we check the `symbol` the `intrinsicName` is `never` and no symbol is assigned, while in the editor it works perfectly fine.

**Comment by kitten** [comment]
We had a similar issue before this related to a `moduleResolution` issue, so we'll likely have to go through `tsconfig.json` settings and see whether one of them affects the run 🤔

**Comment by kitten** [comment]
Just a heads up, I haven't forgotten about this, but the behaviour is really odd. The result of `gql.tada`'s `graphql` calls seems to infer to `never` unless I symlink my local build of `gql.tada` into the reproduction. However, my local build is identical to the currently published version, so there seems to be something weird going on with some dependencies.

**Comment by kitten** [comment]
@dnlsandiego: This proved to be hard to reproduce, but it was easy to track down in the end. I'm not sure how we didn't catch this in other reproductions/examples, but it basically came down to a missing `realpath` resolution, which is required with `pnpm`
