### ISSUE TITLE
Add documentation on how to debug

### ISSUE THREAD

**Issue by ThallesP** [0no-co/gql.tada#29]
Hi, I had some problems with gql.tada but I've no idea on how to debug this (I'm using VSCode).

Is there anyway to debug (logs in specific)?

**Comment by JoviDeCroock** [comment]
Define problems, if it's with the LSP not working it might be because you aren't using the workspace TS version and if you are you can open the TS server logs with the VSCode command line. If it's about tada we'll need info on what's going wrong.

PS the LSP is in a different repo

**Comment by ThallesP** [comment]
> Define problems, if it's with the LSP not working it might be because you aren't using the workspace TS version and if you are you can open the TS server logs with the VSCode command line. If it's about tada we'll need info on what's going wrong.
> 
> PS the LSP is in a different repo

It's the LSP as I'm not getting any `graphql-env.d.ts`. I've added the `settings.json` to use the node_modules one but no success so far.

**Comment by ThallesP** [comment]
> > Define problems, if it's with the LSP not working it might be because you aren't using the workspace TS version and if you are you can open the TS server logs with the VSCode command line. If it's about tada we'll need info on what's going wrong.
> > PS the LSP is in a different repo
> 
> It's the LSP as I'm not getting any `graphql-env.d.ts`. I've added the `settings.json` to use the node_modules one but no success so far.

And I've no indication that it's doing something, that's why I wanted to see some kind of logs.
About the LSP logs, where can I find it? Couldn't find it through the "output" tab in VSCode

**Comment by JoviDeCroock** [comment]
You can look on the bottom right in VSCode when on a TS file whether or not you are using the workspace version. The settings.json won't automatically switch as VSCode thinks that's not secure, when you go to a TS file you will get a prompt to switch to the workspace version that's what the second property does.

I will also move this issue to the proper repo.

**Comment by ThallesP** [comment]
> You can look on the bottom right in VSCode when on a TS file whether or not you are using the workspace version. The settings.json won't automatically switch as VSCode thinks that's not secure, when you go to a TS file you will get a prompt to switch to the workspace version that's what the second property does.
> 
> I will also move this issue to the proper repo.

It looks like I'm using the workspace version
![image](https://github.com/0no-co/gql.tada/assets/76017384/ce149f40-9581-40f7-8201-990201b00601)

**Comment by ThallesP** [comment]
Got the logs, but nothing useful
![image](https://github.com/0no-co/gql.tada/assets/76017384/7bd45fb2-64cc-49ce-a1b9-45c53299acc7)

**Comment by JoviDeCroock** [comment]
Well then you can open the TSserver logs in VSCode and look for crashes/... https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code

**Comment by ThallesP** [comment]
Got the error:
```json
Got invalid response {"errors":[{"locations":[{"column":7,"line":3}],"message":"Field __schema is too complex: complexity is 217 and maximum is 200"},{"locations":[{"column":5,"line":2}],"message":"Operation IntrospectionQuery is too complex: complexity is 217 and maximum is 200"}]}
```

Is there any configuration file to change the max complexity?

**Comment by ThallesP** [comment]
In case you need the schema: https://evm-sidechain.xrpl.org/graphiql

**Comment by JoviDeCroock** [comment]
That's coming from your server when fetching the introspection

**Comment by ThallesP** [comment]
> That's coming from your server when fetching the introspection

That's weird, I don't get that error when using Insomnia or CURL.
I can try to get the introspection json and use that directly

**Comment by erickreutz** [comment]
I ran into this problem. I have custom directives in my schema and I'm getting "Unknown directive" errors from `GraphQLSP`. Is there a plan to support unknown directives?

**Comment by osadi** [comment]
I had the same problem. No types generated.

Followed the above steps to get logging for the TS Server working and found an issue (It wasn't tagged with ` [GraphQLSP]`):

```
Err 232   [09:38:32.346] Exception on executing command unknown:
    Directive "@aws_oidc" may not be used on OBJECT.
    Directive "@aws_api_key" may not be used on OBJECT.
```

These directives come from AWS AppSync, and to get this 'working' I added the directives to the schema like so:

```graphql
directive @aws_oidc on OBJECT
directive @aws_api_key on OBJECT
```
Available locations can be found here https://spec.graphql.org/October2021/#TypeSystemDirectiveLocation

This generates the introspection for me, but: I haven't deployed this yet. I'm guessing that defining them will mess up something on the AWS side  :) 

One solution could be if the schema config could handle a list of schemas? I'm thinking I then could provide `GraphQLSP` with an extra schema holding the directives, just for type generation, and deploy the schema without the declarations.. maybe.. Or run the schema trough a preprocessing step when synthesizing in CDK and strip out the directives.
