### ISSUE TITLE
Issue: Explicit type annotation is needed when initialising graphQL tada

### ISSUE THREAD

**Issue by JFSoler** [0no-co/gql.tada#376]
### Describe the bug

build fails with typescript v5.5 onwards while having the option "declaration" enabled in tsconfig.
```ts
// tsconfig.json

{
  "compilerOptions": {
    "declaration": true,
    ...
  }
}
```

```ts
// graphql.ts

import { initGraphQLTada } from 'gql.tada';
import type { introspection } from './generated/supergraph.d.ts';

export const graphql = initGraphQLTada<{
  disableMasking: true;
  introspection: introspection;
}>();

```

raised error:
```
error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

export const graphql = initGraphQLTada<{
```

### gql.tada version

gql.tada v1.8.6

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
That's a new sanity check afaik, but nothing we can do about this afaik. The only way around this is to declare the `graphql` function's type manually in a declaration file. Otherwise, TypeScript will likely not recognise that it can reuse the existing declaration, since it's separate from the output.

FWIW, it's not a good idea to share the `graphql` function via declarations in this way. There might be ways around this, but in general, this isn't built to be shared but to be used in a "local" code base in your repository or monorepo

**Comment by JFSoler** [comment]
> That's a new sanity check afaik, but nothing we can do about this afaik. The only way around this is to declare the graphql function's type manually in a declaration file. Otherwise, TypeScript will likely not recognise that it can reuse the existing declaration, since it's separate from the output.

At least I grabbed all the internal definitions from `gql-tada.d.ts` so that I could have `schemaOfSetup` and `configOfSetup` in the `graphql.ts` file and that fixed the build issue. Example:

```ts
// all the internal type definitions from gql-tada.d.ts file

interface Setup extends AbstractSetupSchema {
  disableMasking: true;
  introspection: introspection;
}

export const graphql: GraphQLTadaAPI<schemaOfSetup<Setup>, configOfSetup<Setup>> = initGraphQLTada<Setup>();
```

> FWIW, it's not a good idea to share the graphql function via declarations in this way. There might be ways around this, but in general, this isn't built to be shared but to be used in a "local" code base in your repository or monorepo

what do you mean by "local" code base? I was following what's on https://gql-tada.0no.co/get-started/installation#initializing-gql-tada-manually to write GQL documents.

**Comment by kitten** [comment]
You were following it, but in a typical "app" build output, I wouldn't expect declarations to be generated, so I assume it's isolated in a package that isn't aliased in a monorepo, but instead shared declarations, or is a library that's being built.
But If you're just testing this all good.

I think we can make this more ergonomic though
