### ISSUE TITLE
RFC: Helper to get any type in schema

### ISSUE THREAD

**Issue by oceandrama** [0no-co/gql.tada#390]
## Summary
Now there are helpers to get result of query or mutation and its variables, but it's very hard to get type of concrete enum, input type etc.
For example, if I want to get `UserRole` enum I need to do something like this
```graphql
enum UserRole {
  USER
  ADMIN
}

input UserFilterInput {
  role: UserRole
}

type Query {
  users(filter: UserFilterInput ): [User!]!
}
```
```typescript
import { graphql, type VariablesOf } from "gql.tada"

const query = graphql(`
  query users($filter: UserFilterInputType) {
      users(filter: $filter) {
          id
      }
  }`
)

type UserRole = NonNullable<NonNullable<VariablesOf<typeof query>["filter"]>["role"]>
```

## Proposed Solution
It will be very usefull to have helper like
```typescript
import { initGraphQLTada, TypeOf } from 'gql.tada'

const graphql = initGraphQLTada(...)

type UserRole = TypeOf<"UserRole">
type UserFilterInput = TypeOf<"UserFilterInput">
type User = TypeOf<"User">
```

**Comment by kitten** [comment]
See: https://gql-tada.0no.co/reference/gql-tada-api#graphql-scalar
This works on any input type

As per `TypeOf<"User">`, you can't retrieve a concrete type for an object type.
See: https://gql-tada.0no.co/reference/gql-tada-api#graphql-scalar
