### ISSUE TITLE
gql.tada npm scripts open file dialog in windows

### ISSUE THREAD

**Issue by onionhammer** [0no-co/gql.tada#404]
### Describe the bug

When creating a package.json script, like the following:

```json
"scripts": {
    "generate-persisted": "gql.tada generate persisted --output persisted-documents.json -c ./tsconfig.app.json",
}
```

running `npm run generate-persisted` works on Mac, but on windows opens a file dialog (probably the ".tada" part of the script name?)

### gql.tada version

^1.8.9

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
On Windows, you'll have to use the command as "gql-tada" rather than "gql.tada". We'll have to update the docs accordingly at some point
