### ISSUE TITLE
Nested Union Fragment fields are not getting resolved

### ISSUE THREAD

**Issue by freddieerg** [0no-co/gql.tada#415]
### Describe the bug

If I have a fragment that is on a union type

```
const WhatWeDoPageContentDynamicZoneFragment = graphql(`
    fragment WhatWeDoPageContentDynamicZoneFragment on WhatWeDoPageContentDynamicZone
    @_unmask {
        __typename
        ... on ComponentComponentsQuote {
            __typename
            author
        }

        ... on ComponentComponentsCover {
            __typename
            title
            subtitle
            coverImage {
                url
            }
        }
    }
`);
```

and I add that to another fragment:

```
const WhatWeDoPageFragment = graphql(
    `
        fragment WhatWeDoPageFragment on WhatWeDoPage @_unmask {
            content {
                __typename
                ...WhatWeDoPageContentDynamicZoneFragment
            }
        }
    `,
    [WhatWeDoPageContentDynamicZoneFragment]
);
```

The only field that gets resolved is __typename.

I would expect to get an array containing ComponentComponentsQuote and ComponentComponentsCover with the fields I have specified.

### gql.tada version

gql.tada 1.8.10

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Without a reproduction or at the very least a schema of the relevant parts, this isn't something we could feasibly look into (or alternatively, explain, if it's expected behaviour). Sorry! 😅

**Comment by freddieerg** [comment]
Hey, sorry this definitely needed some more explanation / was not explained well. I actually just worked out the issue isn't with gql.tada but Apollo Client being unable to resolve fragments with unions without explicitly defining them in the InMemoryCache. See explanation [here](https://www.apollographql.com/docs/react/data/fragments#using-fragments-with-unions-and-interfaces).

I'll close this issue and hopefully someone may find it useful in the future.

**Comment by kitten** [comment]
Ah, gotcha! I haven't looked into this for a while, but we did consider that we may have to add extra generators for Apollo's cache and ural Graphcache in the future to make that part easier

**Comment by freddieerg** [comment]
Yeh would definitely be nice to have but I used their [recommended solution](https://www.apollographql.com/docs/react/data/fragments#generating-possibletypes-automatically) and it works quite nicely, I just have a script now where I generate the schema, then generate output, then create a possibleTypes json which I provide to Apollo's InMemoryCache. 

I guess maybe in the CLI it could be cool to have generatePossibleTypes or just have it as an option for generateSchema or generateOutput.
