### ISSUE TITLE
check command failed if schema is not available

### ISSUE THREAD

**Issue by oceandrama** [0no-co/gql.tada#418]
### Describe the bug

It looks like `check` command should only validate queries with existing introspection (and it works exactly like this), but before that it also checks for schema availability, which may not be possible, for example, in ci/cd without internet access. I think this is unneccesary step, which may be skipped

### gql.tada version

gql.tada v1.8.10

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
The `check` command is able to output any diagnostics that the GraphQLSP plugin outputs in your editor/IDE. As such, it needs the schema and operates on schema-based validation rules as well.

If your schema isn't permanently available (for example if it's built up and/or stored in a different repo) you may want to consider downloading it and committing it to your repo: https://gql-tada.0no.co/get-started/workflows#downloading-schemas
