### ISSUE TITLE
maskFragments returns `never` for custom scalars with array fields

### ISSUE THREAD

**Issue by awinograd** [0no-co/gql.tada#72]
### Describe the bug

Thanks for a really exciting gql library! I'm testing this out in my codebase as a replacement for graphql-code-generator and typed-graphql-builder.

I tried creating a reproduction using the linked example repo, but I'm unable to get `./src/graphql-env.d.ts` to update with my schema changes for some reason (even though I have no issues in my actual app) :/

My actual issue is as follows. 

```graphql
scalar OpaqueObject

type User {
  field: OpaqueObject
}
```

```ts
export const graphql = initGraphQLTada<{
  introspection: introspection;
  scalars: { OpaqueObject: { innerField: [] } };
}>();

const MyFragment = graphql(`
  fragment MyFragment on User {
    field
  }
`)

// data is type `never` but should be a properly wrapped fragment type
const data = maskFragments([MyFragment], { field: { innerField: [] } })
```

Whenever a scalar has an internal `array` property, the `maskFragments` function returns never. It properly supports nested object / other complex data types.

### gql.tada version

1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Just leaving a note here, as I haven't responded yet. I haven't had time to look into this yet, because I'd like to add failing tests for this at the same time, but the tests would be a little longer than some simple additions, I reckon.

I think there's probably a simple bug in a recursive transform type here, since this is specific to `maskFragments`, so it should be an easy fix, but just noting that the delay here is since I know it will require a bit more time to write a unit test for this ✌️

**Comment by awinograd** [comment]
@kitten Thanks for the note and for your effort on this library! I look forward to giving it a spin again with this patch. We've been able to convert a large chunk of our usage already and it's been great.

**Comment by JoviDeCroock** [comment]
The discrepancy is pretty normal to TypeScript I feel, we will see the `[]` as `never[]` on the actual JS Object while we will see an Array literal as a type on our `DocumentResult` which leads to this.

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG0C6BuAUD0kUASggK4A2SqA3jlPVAJYAmAXFIgE6MB2A5rgZRgCYOziIcAXzwBjAPY9EUTmUoootIS3YByAIy6ANHQYjE7TNLwFoADw235AMxVrguW1BAaS8CsA4QA

For instance the following works, you can replace `never` with anything else

```
export const graphql = initGraphQLTada<{
  introspection: introspection;
  scalars: { OpaqueObject: { innerField: never[] } };
}>();

const MyFragment = graphql(`
  fragment MyFragment on User {
    field
  }
`)

// data is type `never` but should be a properly wrapped fragment type
const data = maskFragments([MyFragment], { field: { innerField: [] as never[] } })
```

**Comment by awinograd** [comment]
@JoviDeCroock is your suggestion to cast array fields inside scalars as `never` going forward? I can confirm it is a viable workaround on my end if this case is not distinguishable in the library types

**Comment by kitten** [comment]
Closing since this is essentially intended behaviour for the time being, seeing that `readonly (infer U)[]` will always evaluate and cascade to `never` with how fragment re-masking is currently done.

**Comment by awinograd** [comment]
I know this was closed as intended behavior but just wanted to let you know that I recently upgraded to 1.4.1 and this issue is resolved. I no longer observe the "bug" reported in the OP
