### ISSUE TITLE
The Prettier problem

### ISSUE THREAD

**Issue by xamir82** [0no-co/gql.tada#91]
### Describe the bug

When using the `graphql` function and passing a fragment array as the second argument, Prettier (the ubiquitous code formatter) stacks the two arguments on top of each other, which in turns causes syntax highlighting to be lost:
  

https://github.com/0no-co/gql.tada/assets/119128472/d99e2177-ac21-4442-8f20-e0b2c59df5c7

Is there any solution to this problem? And can it be fixed upstream by `gql.tada`?

### gql.tada version

1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
in progress yes https://github.com/graphql/graphiql/pull/3518

**Comment by xamir82** [comment]
@JoviDeCroock Ah, nice. Thank you.
