### ISSUE TITLE
Include the source string as part of `graphql()`'s returned object

### ISSUE THREAD

**Issue by aradalvand** [0no-co/gql.tada#93]
Currently `graphql()` returns a `DocumentNode` on which you have run the `print` function of the `graphql` package if you actually want the stringified query that you can send to a GraphQL server; but calling `print` on the AST seems wasteful since we already did have the "printed" version, right in the source code.

Wouldn't it make sense for `TadaDocumentNode` to also include, for example, a `.toString()` method that avoids the overhead of the AST-to-string processing that `print` entails, and gives you the original string (along with all the fragments concatenated) directly?

**Comment by kitten** [comment]
I'll have to reject this, as I don't see a good argument for this to be done.

The GraphQL.js AST is, while not strictly speaking standardised by the spec — but closely following the AST spec, the de-facto standard to handle GraphQL documents in GraphQL clients.

Additionally, parsing and printing is also useful to:
- normalize the output string of the query
- ensure that the string you have matches mutable modifications made to the AST

If you were to just use the string, of course, that could be passed through but the reality is that given a GraphQL client “just” sending the document as-is while also wanting typings for the execution result is a rather niche use-case, and not in scope for what this library aims to achieve.

`graphql.js` also has an alternative to this; which is the `Source` interface that can be placed on ASTs, but it's also not very standardised and not always used/provided, in all implementations or code generators, so it's often disregarded, as it also has no connection to the spec (unlike the AST shape itself)

If you're concerned about the size of the `print` function, for example, `gql.tada` doesn't use the `graphql.js` library, i.e. the reference implementation. It instead relies on `@0no-co/graphql.web`: https://github.com/0no-co/graphql.web
You can use the `print` function from it instead.

If you're using `graphql` in other places, we also have a drop-in replacement for client-side functions that are commonly used from `graphql.js`, which is a project called `graphql-web-lite`, which wraps around `graphql.web`: https://github.com/0no-co/graphql-web-lite

---

re. your other issue btw, you're welcome to ask questions in GitHub discussions or our Discord. Submitting RFC-type issues isn't a very productive way for us to engage with discussions or questions ❤️ 😅

**Comment by aradalvand** [comment]
@kitten Could you please check the Discord server? I did ask some questions there but it doesn't seem like it's frequently visited by you guys.
